### ISSUE TITLE
replace travis with actions

### ISSUE THREAD

**Issue by gr2m** [semantic-release/npm-registry-docker#51]
Part of https://github.com/semantic-release/semantic-release/issues/1692

### Todos

- [ ] delete `.travis.yml`
- [ ] create `.github/workflows/{test,release}.yml` (copy from https://github.com/semantic-release/npm/tree/master/.github/workflows)
- [ ] remove `package-lock.json` from `.gitignore`
- [ ] delete `.npmrc` and `.yarnrc`
- [ ] README
	- [ ] remove travis/codecov badges
	- [ ] add actions badge instead (replace `REPO NAME HERE` ;): `[![Build Status](https://github.com/semantic-release/[REPO NAME HERE]/workflows/Test/badge.svg)](https://github.com/semantic-release/[REPO NAME HERE]/actions?query=workflow%3ATest+branch%3Amaster)`
- [ ] create `package-json.lock`
- [ ] add to package.json:
	- [ ] `test:ci` script which doesn't run `lint` pre script
	- [ ] renovate config 

		```
		  "renovate": {
		    "extends": [
		      "github>semantic-release/.github"
		    ]
		  }
		```
- [ ] update branch protection: remove required status by Travis and Codecov, add required status for "test" (wait for first build of PR)
